#pragma once
#define _WINSOCK_DEPRECATED_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS

#include <WinSock2.h>
#include <stdlib.h>
#include <ws2tcpip.h>
#include <locale.h>
#include <Windows.h>
#include <time.h>
#include <process.h>
#include <map>
#include <vector>
#include <conio.h>
#include <unordered_map>
#include <stack>
#include <stdio.h>
#include <strsafe.h>
#include <algorithm>
#include <mstcpip.h>